2024-09-03T22:44:32.5175186Z ##[group]Run cmake -B /home/runner/work/pi-network-cloud-automation/pi-network-cloud-automation/build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -S /home/runner/work/pi-network-cloud-automation/pi-network-cloud-automation
cmake -B /home/runner/work/pi-network-cloud-automation/pi-network-cloud-automation/build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release -S /home/runner/work/pi-network-cloud-automation/pi-network-cloud-automation
shell: /usr/bin/bash -e {0}
CMake Error: The source directory "/home/runner/work/pi-network-cloud-automation/pi-network-cloud-automation" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
version: 2

updates:
  # 1. تحديث التبعيات الخاصة بـ npm في الواجهة الأمامية
  - package-ecosystem: "npm"  # نظام إدارة الحزم
    directory: "/frontend"  # مسار ملف package.json
    schedule:
      interval: "weekly"  # يتم فحص التحديثات أسبوعيًا
    open-pull-requests-limit: 5  # حد أقصى لطلبات السحب المفتوحة
    commit-message:
      prefix: "fix"  # بادئة رسالة الالتزام
    ignore:
      - dependency-name: "some-package"  # استبعاد حزمة معينة من التحديثات

  # 2. تحديث التبعيات الخاصة بـ npm في الواجهة الخلفية
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "fix"
    ignore:
      - dependency-name: "some-package"  # استبعاد حزمة معينة من التحديثات

  # 3. مراقبة تبعيات GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"  # يتم فحص التحديثات يوميًا
    commit-message:
      prefix: "chore"  # بادئة رسالة الالتزام
    ignore:
      - dependency-name: "actions/setup-node"  # استبعاد حزمة معينة من التحديثات
