name: Terragrunt Example Job

on:
  push:
    branches:
      - main  # أو الفرع الذي تريد تتبعه

jobs:
  terragrunt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'  # أو الإصدار الذي تحتاجه

      - name: Install Terragrunt
        run: |
          curl -Lo terragrunt https://github.com/gruntwork-io/terragrunt/releases/latest/download/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/

      - name: Run Terragrunt
        run: |
          cd path/to/your/terragrunt/config  # استبدل هذا بالمسار الصحيح
          terragrunt apply --auto-approve
